#
# JIX InnerVault Blog Configuration
#

# Site Identity
name: InnerVault Journal
description: "A digital notebook of ideas, experiments, and evolution."
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Author Details (Optional future use)
author: "Jixntcc"

# Social / Footer Links
footer-links:
  email: tmkarmax@gmail.com
  github: jixntcc
  twitter: jixntcc
  instagram: jix.innervault
  linkedin: www.hopp.bio/jixntcc
  youtube: https://www.youtube.com/@jixntcc
  rss: true

# Comments (optional)
disqus: 

# Analytics (optional)
google_analytics: 

# URL Configuration
url: "https://jixntcc.github.io"
baseurl: ""

# Permalinks
permalink: /:year/:month/:day/:title/

# Version & Markdown
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass (Styling)
sass:
  style: :expanded

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Excluded from _site build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
